modules:
  protofiles:
    type: ProtoFiles
    network: ./assets/adhoc_routing/no_updates/network.binpb
    population: ./assets/adhoc_routing/no_updates/agents.binpb
    vehicles: ./assets/adhoc_routing/no_updates/vehicles.binpb
    ids: ./assets/adhoc_routing/no_updates/ids.binpb
  partitioning:
    type: Partitioning
    num_parts: 1
    method: Metis
  output:
    type: Output
    output_dir: ./test_output/simulation/adhoc_routing/no_updates/one_part
  routing:
    type: Routing
    mode: AdHoc
  simulation:
    type: Simulation
    start_time: 0
    end_time: 86400
    sample_size: 1.0

