[package]
name = "rust_q_sim"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { verion = "1.0.137", features = ["derive"] }
quick-xml = { version = "0.23.0", features = ["serialize"] }
flate2 = { version = "1.0.24" }
rand = "0.7.3"
metis = "0.1.1"
tracing = "0.1.35"
tracing-subscriber = "0.3.14"
tracing-appender = "0.2"