[package]
name = "rust_q_sim"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.137", features = ["derive"] }
serde_json = "1.0.93"
quick-xml = { version = "0.23.0", features = ["serialize"] }
flate2 = { version = "1.0.24" }
rand = "0.8.5"
metis = { git = "https://github.com/Janekdererste/metis-rs"}
flexi_logger = { version = "0.22", features = ["async"] }
log = "0.4"
clap = { version = "4.0.29", features = ["derive"] }
fast_paths = "0.2.0"
rust_road_router = { git = "https://github.com/paulheinr/rust_road_router", branch = "clean_log" }
mpi = "0.6"
geo = "0.23.1"
# dependencies for serialization with protobuf
prost = "0.11.5"
# bytes replaces the signature of std::io::Cursor to implemnt Buf somehow...
bytes = "1.3.0"
serial_test = "1.0.0"
wait-timeout = "0.2.0"
kiddo = "2.0.2"

[build-dependencies]
# generates types based on .proto files
prost-build = "0.11"
# provides the protoc compiler - this makes the build slow but one doesn't need to
# install the protoc compiler as prerequisite.
protobuf-src = "1.1.0"

[profile.bench]
debug=true
