[package]
name = "rust_q_sim"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.137", features = ["derive"] }
serde_json = "1.0.93"
quick-xml = { version = "0.23.0", features = ["serialize"] }
flate2 = { version = "1.0.24" }
rand = "0.8.5"
metis = "0.1.2"
flexi_logger = { version = "0.22", features = ["async"] }
clap = { version = "4.0.29", features = ["derive"] }
# point to the github repo directly because we need a more recent version of bindgen. Otherwise the build fails
# due to some incompatibility starting with macOs 13.6
mpi = { git = "https://github.com/rsmpi/rsmpi", rev = "1622101c9fc3a78620e9649f7f895616289d3558" }
# dependencies for serialization with protobuf
prost = "0.11.5"
# bytes replaces the signature of std::io::Cursor to implemnt Buf somehow...
bytes = "1.3.0"
serial_test = "1.0.0"
wait-timeout = "0.2.0"
tracing = "0.1"
tracing-subscriber = { version = "0.3.0", features = ["json", "fmt", "std", "registry"] }
tracing-appender = "0.2"
itertools = "0.10.5"
assert_approx_eq = "1.1.0"
nohash-hasher = "0.2.0"
rand_distr = "0.4.3"
serde_path_to_error = "0.1.14"
geo = "0.26.0"
ahash = "0.8.6"
keyed_priority_queue = "0.4.1"
xml = "0.8.10"
lz4_flex = "0.11.1"

[build-dependencies]
# generates types based on .proto files
prost-build = "0.11"
# provides the protoc compiler - this makes the build slow but one doesn't need to
# install the protoc compiler as prerequisite.
protobuf-src = "1.1.0"

[profile.bench]
debug = true

[profile.release]
debug = true
