[package]
name = "rust_q_sim"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.137", features = ["derive"] }
quick-xml = { version = "0.23.0", features = ["serialize"] }
flate2 = { version = "1.0.24" }
rand = "0.7.3"
metis = "0.1.1"
flexi_logger = { version = "0.22" , features = ["async"]}
log = "0.4"
clap = { version = "4.0.29", features = ["derive"] }
