modules:
  xmlfiles:
    type: XmlFiles
    network: ./assets/equil/equil-network.xml
    population: ./assets/equil/equil-plans.xml.gz
    vehicles: ./assets/equil/equil-vehicles.xml
  protfiles:
    type: ProtoFiles
    network: ./assets/equil/equil-network.binpb
    population: ./assets/equil/equil-population.binpb
    vehicles: ./assets/equil/equil-vehicles.binpb
    ids: ./assets/equil/equil-ids.binpb
  partitioning:
    type: Partitioning
    num_parts: 2
    method: Metis
  output:
    type: Output
    output_dir: ./output
  routing:
    type: Routing
    mode: UsePlans
  simulation:
    type: Simulation
    start_time: 0
    end_time: 86400
    sample_size: 1.0

