modules:
  protofiles:
    type: ProtoFiles
    network: ./assets/equil/equil-network.binpb
    population: ./assets/equil/equil-plans.binpb
    vehicles: ./assets/equil/equil-vehicles.binpb
    ids: ./assets/equil/ids.binpb
  partitioning:
    type: Partitioning
    num_parts: 2
    method: !Metis
  output:
    type: Output
    output_dir: /Users/janek/Documents/rust_q_sim/equil/output/size
    profiling: !CSV
      level: TRACE
  routing:
    type: Routing
    mode: UsePlans
  simulation:
    type: Simulation
    start_time: 0
    end_time: 10
    sample_size: 1.0
    stuck_threshold: 1000

