name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
#  set-up:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v3
#      - name: Install InertialFlowCutter libraries
#        run: |
#          sudo apt-get update &&
#          sudo apt-get -y install libtbb-dev readline8 readline-dev zlib1g-dev
#      - name: Clone InertialFlowCutter
#        uses: actions/checkout@v3
#        with:
#          repository: paulheinr/InertialFlowCutter
#          ref: master
#          submodules: true
#      - name: Install InertialFlowCutter
#        run: |
#          cd InertialFlowCutter
#          mkdir build
#          cd build
#          cmake -DCMAKE_BUILD_TYPE=Release ..
#          make

  build:
#    needs: set-up
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install
      run: sudo apt -y install libclang-dev libmetis-dev llvm-dev libopenmpi-dev
    - name: Set Rust to nightly
      run: rustup default nightly
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose