name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  set-up:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install InertialFlowCutter libraries
        run: |
          sudo apt-get update &&
          sudo apt-get -y install libreadline8 libreadline-dev zlib1g-dev
      - name: Clone InertialFlowCutter
        uses: actions/checkout@v3
        with:
          repository: paulheinr/InertialFlowCutter
          ref: master
          submodules: true
          path: ./InertialFlowCutter
      - name: Install TBB
        run: |
          REM Do our experiments in %TMP%
          cd /tmp
          REM Clone oneTBB repository
          git clone https://github.com/oneapi-src/oneTBB.git
          cd oneTBB
          REM Create binary directory for out-of-source build
          mkdir build && cd build
          REM Configure: customize CMAKE_INSTALL_PREFIX and disable TBB_TEST to avoid tests build
          cmake -DCMAKE_INSTALL_PREFIX=/tmp/manual_installed_tbb -DTBB_TEST=OFF ..
          REM Build "release with debug information" configuration 
          cmake --build . --config relwithdebinfo
          REM Install "release with debug information" configuration 
          cmake --install . --config relwithdebinfo
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
      - name: Install InertialFlowCutter
        run: |
          cd ./InertialFlowCutter
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release ..
          make

  build:
    needs: set-up
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install
      run: sudo apt -y install libclang-dev libmetis-dev
    - name: Set Rust to nightly
      run: rustup default nightly
    - name: Build
      run: cargo build --verbose

  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Run tests
      run: cargo test --verbose