name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  INERTIAL_FLOW_CUTTER_HOME_DIRECTORY: ./InertialFlowCutter

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install other libraries
        run: sudo apt -y install libclang-dev llvm-dev libmetis-dev libopenmpi-dev
      - name: Build
        run: cargo build
      - name: Install mpirun
        run: cargo install --force cargo-mpirun
      - name: Run tests
        run: cargo test --verbose