name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  set-up:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install InertialFlowCutter libraries
        run: |
          sudo apt-get update &&
          sudo apt-get -y install libtbb-dev libreadline8 libreadline-dev zlib1g-dev libopenmpi-dev libopenmpi3
      - name: Clone InertialFlowCutter
        uses: actions/checkout@v3
        with:
          repository: paulheinr/InertialFlowCutter
          ref: master
          submodules: true
          path: ./InertialFlowCutter
      - name: Install TBB
        run: |
          cd /tmp
          git clone https://github.com/oneapi-src/oneTBB.git
          cd oneTBB
          mkdir build && cd build
          cmake -DCMAKE_INSTALL_PREFIX=/tmp/manual_installed_tbb -DTBB_TEST=OFF ..
          cmake --build . --config relwithdebinfo
          cmake --install . --config relwithdebinfo
#      - name: Setup tmate session
#        uses: mxschmitt/action-tmate@v3
      - name: Show TBB information
        run: dpkg -L libtbb-dev
      - name: Install InertialFlowCutter
        run: |
          cd ./InertialFlowCutter
          mkdir build
          cd build
          cmake --debug-find -DCMAKE_BUILD_TYPE=Release ..
          make

  build:
    needs: set-up
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install
      run: sudo apt -y install libclang-dev libmetis-dev
    - name: Set Rust to nightly
      run: rustup default nightly
    - name: Build
      run: cargo build --verbose

  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Run tests
      run: cargo test --verbose