name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:

  build:
#    needs: set-up
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3

#    - name: Install
#      run: sudo apt -y install libclang-dev libmetis-dev
#    - name: Set Rust to nightly
#      run: rustup default nightly
#    - name: Build
#      run: cargo build --verbose
#
#  test:
#    needs: build
#    runs-on: ubuntu-latest
#
#    steps:
#    - name: Run tests
#      run: cargo test --verbose